body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package are you needing help?
      options:
        - Panel builder
        - Table builder
        - Form builder
        - Infolist builder
        - Actions
        - Notifications
        - Widgets
        - Other
      default: 0
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Please provide the full version of the package you have installed.
      placeholder: v3.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: How can we help you?
      description: What is happening? What you are trying to do? What you did? What is the issue/error?
    validations:
      required: true
