body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package are you experiencing the problem?
      options:
        - Panel builder
        - Table builder
        - Form builder
        - Infolist builder
        - Actions
        - Notifications
        - Widgets
        - Other
      default: 0
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Please provide the full version of the package you have installed.
      placeholder: v3.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: What happened when you experienced the problem?
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction repository (optional)
      description: The URL of a public GitHub repository which reproduces the problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
